### ISSUE TITLE
NullReferenceException on deserializing inherited classes

### ISSUE THREAD

**Issue by gabrielfetz** [wojtpl2/ExtendedXmlSerializer#241]
Hello!
There's a specific situation in our project where we use inheritance to deal with different versions of layouts from the received xml files. We create new classes in a different namespace that inherits from the "old version" classes, then we do the properly modifications on them to support the newer layouts of the xml file. I'm getting a NullReferenceException when deserializing these classes, even when the xml file is adjusted as said on #239. I suspect the solution for this problem is something with the EnableImplicitTyping methods, but I've tested some of them without success.
You can download my PoC project here: https://github.com/gabrielfetz/PoCXML.
Thanks again in advance. 😃

**Comment by Mike-EEE** [comment]
Oh man... yeah you found a bug @gabrielfetz NICE WORK. 😅  FWIW it doesn't appear to be due to implicit typing but something with how the lists are resolved with inheritance.

I am looking into this now.

**Comment by gabrielfetz** [comment]
Hi mike!
Thanks again for your fast response!
Actually, i made a terrible mistake. 😒
I totally forgot to change some references on the new classes! Now i fixed that and looks like it's working. I'll make some more tests, commit the changes on Github and keep you informed as well.

**Comment by Mike-EEE** [comment]
Ah, good!  There is still a very big bug here and the reason why we haven't seen it until now is because of how we do unit tests.  

We of course isolate unit tests and subject classes within the test classes.  What that does is create root elements such as `<Issue241Tests-ClassName />`.

However, the problem is that if the property name (`DmDev`) is the same name as the class name (`DmDev`), then the deserializer gets confused and ends up with this error.

Again, the reason why we haven't seen this until now is that `DmDev` would actually be registered as `Issue241Tests-DmDev` in the isolated test.

This is another ugly one, I am afraid.  However, I am sort of sensing that I might be able to address #240 too while we're at it.

HERE GOES NOTHING. 😂

**Comment by Mike-EEE** [comment]
Ewwww... yeah, that was a really bad one.  Basically, we have to check if the member name is the same as its collection type name (if it is a collection type) and then emit a special attribute for it.  Not ideal at all but there is little choice here, as this is only for a special condition.

While it doesn't really impact emitting/writing much, it does hit us with the reading (deserialization) as we do need to check now to see if that attribute exists for each deserialization context, which is a performance hit.

In any case, it does work now.  If you do run into any further additional problems here, please check out the preview feed to see if it fixes it:

https://www.myget.org/F/wojtpl2/api/v3/index.json

If you experience any other/further issues please let us know.  Otherwise I will probably kick off `2.1.17` in a few days.

**Comment by gabrielfetz** [comment]
Thanks for all your effort on this issue! 
I said before that I made it work by fixing my reference mistake in "NewVersion.EvtDeslig", but I also deleted two classes: "NewVersion.DmDev" and "NewVersion,VerbasResc". Turns out that what made it work wasn't the reference fix, but the exclusion of "NewVersion.DmDev" class. When I created it again to execute more tests, the problem came back too.

I updated the ExtendedXmlSerializer in the PoCXML via MyGet, however, the exception persists. Maybe I'm doing something really stupid here 😆

**Comment by Mike-EEE** [comment]
Ah!  Yes I forgot to mention that.  You will need to update your data files to make use of this new attribute.  I got the PoCXML working with the following XML:

```
<EvtDeslig Id="ID1234567891234567891234567891234567" Version="v02_05_00">
  <InfoDeslig xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:type="InfoDeslig">
    <VerbasResc exs:type="VerbasResc">
      <DmDev exs:member="true">
        <DmDev>
          <IdeDmDev>RESCISAO0000000001</IdeDmDev>
        </DmDev>
      </DmDev>
    </VerbasResc>
    <MudancaCPF>
      <NovoCPF>00000000001</NovoCPF>
    </MudancaCPF>
  </InfoDeslig>
</EvtDeslig>
```

Hopefully it works for you. 🤞

Also make note of the `exs:type` attributes as well.  One thing you can try doing is create a temp model of what you expect and call `Serialize` on that to get the generated XML from EXS, and then compare that to the XML that is being passed back in.

Also also. :)  If you really need that XML and cannot change it, consider using XSLT to transform it into the expected/ideal XML for EXS. 👍

**Comment by gabrielfetz** [comment]
Hey Mike!
It worked really fine now! Thank you for your time and help!!
Best regards!

**Comment by Mike-EEE** [comment]
Derp!  I *totally* forgot about this.  Deploying `2.1.17` now!

**Comment by Mike-EEE** [comment]
Woohoo... it works, @wojtpl2:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Alright @gabrielfetz you should be good to go now if you get from the public nuget.  Sorry for the delay!  Please let us know if you have any further issues.  Closing for now.
